[project]
name = "apify-startup-investors"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apify-client>=2.3.0",
    "python-dotenv>=1.2.1",
]
